# Generated by Django 5.2 on 2025-04-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dailytask_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='category',
            field=models.CharField(choices=[('morning', 'Morning Routine'), ('work', 'Work/Study'), ('evening', 'Evening Routine'), ('self_care', 'Self-care')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
