# Generated by Django 5.2 on 2025-04-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dailytask_category_dailytask_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='target',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task_name',
            field=models.CharField(choices=[('water_intake', 'Water Intake (glasses)'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('shower', 'Shower'), ('brushing', 'Brushing Teeth'), ('human_interaction', 'Human Interaction'), ('meditation', 'Meditation'), ('work', 'Work'), ('walk', 'Walk'), ('exercise', 'Exercise'), ('breathing_exercise', 'Breathing Exercise'), ('affirmation', 'Affirmation')], max_length=255),
        ),
    ]
