# Generated by Django 5.2 on 2025-04-14 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dailytask_target_alter_dailytask_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='note',
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task_name',
            field=models.CharField(max_length=100),
        ),
    ]
