# Generated by Django 5.2 on 2025-04-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_completed_dailytask_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='completed',
            new_name='breakfast',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='target',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='task_name',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='meditation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='shower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='sleep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='water_intake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='workout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
