# Generated by Django 5.2 on 2025-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_journalentry_title_alter_dailytask_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
