# Generated by Django 5.2 on 2025-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_journalentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
