# Generated by Django 5.2 on 2025-04-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_journalentry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, default='Journal Entry', max_length=200),
        ),
    ]
