# Generated by Django 5.2 on 2025-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_todoitem_title_wellnesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnesslog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wellnesslog',
            name='exercise_time',
            field=models.FloatField(help_text='Minutes of exercise'),
        ),
        migrations.AlterField(
            model_name='wellnesslog',
            name='outdoor_time',
            field=models.FloatField(help_text='Hours spent outdoors'),
        ),
        migrations.AlterField(
            model_name='wellnesslog',
            name='screen_time',
            field=models.FloatField(help_text='Hours of screen time'),
        ),
        migrations.AlterField(
            model_name='wellnesslog',
            name='sleep_duration',
            field=models.FloatField(help_text='Hours slept'),
        ),
    ]
